# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YqVtZgYbrXTige8XjI-11weVATKMfmnA
"""

# Es de DUOC UC
pertenece_duoc = input("¿Pertenece a Duoc? (true/false): ")

# Tipo de entrada
tipo_entrada = input("¿Qué tipo de entrada desea? (estreno/normal): ")
if (tipo_entrada == "estreno"):
    precio_entrada = 4800
else:
    precio_entrada = 2900

# Cantidad de entradas
cantidad_entradas = int(input("Cantidad de entradas: "))

# Total Entradas
total_entrada = precio_entrada * cantidad_entradas

# Agrega palomitas
agrega_palomitas = input("¿Desea agregar palomitas? (si/no): ")
if (agrega_palomitas == "si"):
    tipo_palomitas = input("¿Qué tamaño de palomitas? (pequeña/mediana/grande): ")
    cantidad_palomitas = int(input("Cantidad de palomitas: "))

    if tipo_palomitas == "pequeña":
        precio_palomitas = 2500 * cantidad_palomitas
    elif tipo_palomitas == "mediana":
        precio_palomitas = 4500 * cantidad_palomitas
    elif tipo_palomitas == "grande":
        precio_palomitas = 7800 * cantidad_palomitas
    else:
        print("Tamaño de palomitas no válido.")
        precio_palomitas = 0
else:
    precio_palomitas = 0

# Selección de bebidas
agregar_bebidas = input("¿Desea agregar bebidas? (si/no): ")
if (agregar_bebidas == "si"):
    tipo_bebida = input("¿Qué tamaño de bebida? (pequeña/mediana/grande): ")
    cantidad_bebidas = int(input("Cantidad de bebidas: "))

    if tipo_bebida == "pequeña":
        precio_bebidas = 1000 * cantidad_bebidas
    elif tipo_bebida == "mediana":
        precio_bebidas = 1250 * cantidad_bebidas
    elif tipo_bebida == "grande":
        precio_bebidas = 2000 * cantidad_bebidas
    else:
        print("Tamaño de bebida no válido.")
        precio_bebidas = 0
else:
    precio_bebidas = 0

# Cálculo del total
descuento_entrada = 0
if (pertenece_duoc == "true"):
    descuento_entrada = total_entrada * 0.3
    total = (total_entrada - descuento_entrada) + precio_palomitas + precio_bebidas
else:
    total = total_entrada + precio_palomitas + precio_bebidas

print(f"Total a pagar: ${total_entrada + precio_palomitas + precio_bebidas}")
print(f"Descuento: ${descuento_entrada}")
print(f"Total a pagar: ${total}")

# Pago y vuelto
pago = int(input("Ingrese el efectivo: "))
if (pago < total):
    print("El pago no es suficiente")
else:
    vuelto = pago - total

# Mostrar resultados
print(f"Vuelto: ${vuelto}")